apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-permissions-cronjob-udl
  namespace: udl
spec:
  schedule: '*/1 * * * *' # Runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-permissions
              image: busybox
              command:
                [
                  'sh',
                  '-c',
                  'chown -R 1000:1000 /home/steam/tf-dedicated && chmod -R g+rw /home/steam/tf-dedicated',
                ]
              volumeMounts:
                - mountPath: /home/steam/tf-dedicated
                  name: tf-data
          volumes:
            - name: tf-data
              hostPath:
                path: /tf/udl
                type: ''
          restartPolicy: OnFailure
