apiVersion: batch/v1
kind: CronJob
metadata:
  name: udl-scripts-create-server
  namespace: udl
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
          - name: udl-scripts-create-server
            image: ghcr.io/dodgeball-tf/udlscripts:latest
            imagePullPolicy: Always
            command: ["bin/create_server"]
            env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_NAME
            - name: STEAM_WEB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: STEAM_WEB_API_KEY
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: udl-scripts-delete-server
  namespace: udl
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
          - name: udl-scripts-delete-server
            image: ghcr.io/dodgeball-tf/udlscripts:latest
            imagePullPolicy: Always
            command: ["bin/delete_server"]
            env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_NAME
            - name: STEAM_WEB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: STEAM_WEB_API_KEY
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: udl-scripts-create-match-details
  namespace: udl
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
          - name: udl-scripts-create-match-details
            image: ghcr.io/dodgeball-tf/udlscripts:latest
            imagePullPolicy: Always
            command: ["bin/create_match_details"]
            env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: DB_NAME
            - name: STEAM_WEB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: udl-secrets
                  key: STEAM_WEB_API_KEY
          restartPolicy: OnFailure
