---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-manager-udl
  namespace: udl
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      namespace: udl
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          affinity: {}
          containers:
            - name: update-manager-udl
              env:
                - name: AUTO_UPDATE_ONLY
                  value: 'true'
                - name: LABEL_SELECTOR
                  value: app=udl
                - name: NAMESPACE
                  value: udl
              command:
                - bash
                - updater.sh
              image: ghcr.io/dodgeball-tf/tf2:sourcemod
              imagePullPolicy: Always
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /home/steam/tf-dedicated/
                  name: tf-data
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - hostPath:
                path: /home/udl
                type: ''
              name: tf-data
  schedule: 0/30 * * * *
  successfulJobsHistoryLimit: 3
  suspend: false
